# Generated by Django 6.0.3 on 2026-04-07 19:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_alter_brand_name_alter_region_name_area_territory_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rsm_name', models.CharField(max_length=100)),
                ('month', models.CharField(max_length=50)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales_records', to='sales.area')),
            ],
        ),
        migrations.DeleteModel(
            name='Brand',
        ),
        migrations.DeleteModel(
            name='Territory',
        ),
    ]
